import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Assento car - Whatsapp bot',
  description: 'Generated by create next app',
};

export default function Home() {
  return (
    <div className="h-screen flex flex-col justify-between items-center">
      <header>header</header>
      <main className="">hello world</main>
      <footer className="">footer</footer>
    </div>
  );
}
